apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: aegis
spec:
  replicas: 1
  selector: { matchLabels: { app: frontend } }
  template:
    metadata: { labels: { app: frontend } }
    spec:
      containers:
        - name: web
          image: mlepnos/aegisguard-frontend:1.1
          ports: [{ containerPort: 5270 }]
          env:
            - { name: ASPNETCORE_URLS, value: "http://0.0.0.0:5270" }
            - { name: ASPNETCORE_ENVIRONMENT, value: "Production" }
            - { name: ApiBaseUrl, value: "http://backend.aegis.svc.cluster.local:8080" }

            # ðŸ‘‡ add these
            - { name: Grafana__BaseUrl, value: "http://aegis.local/grafana" }   # if using ingress host
            - { name: Grafana__DashboardUid, value: "aegis-guard" }             # or leave "" if you want the home
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: aegis
spec:
  type: NodePort
  selector: { app: frontend }
  ports:
    - { name: http, port: 5270, targetPort: 5270, nodePort: 31270 }
